// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruJjAQl6lRmGRUkEJ4tYZ7hxc1QKRQrQ',
    appId: '1:10715035809:web:3677fc5c51f27013ab18e0',
    messagingSenderId: '10715035809',
    projectId: 'emotionspredictor',
    authDomain: 'emotionspredictor.firebaseapp.com',
    storageBucket: 'emotionspredictor.firebasestorage.app',
    measurementId: 'G-6XX76P9RV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-wzw5zjbgwPZIqLB7wTnOtj3r6Y6Y9w',
    appId: '1:10715035809:android:b76da4f240f85ea2ab18e0',
    messagingSenderId: '10715035809',
    projectId: 'emotionspredictor',
    storageBucket: 'emotionspredictor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTPiaodOjwcDJ53PZDi0b4z3hcpXH1j4',
    appId: '1:10715035809:ios:76ba523c58cda6bbab18e0',
    messagingSenderId: '10715035809',
    projectId: 'emotionspredictor',
    storageBucket: 'emotionspredictor.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );
}
